### ISSUE TITLE
Target 'one-to-many' fails with some Python script error

### ISSUE THREAD

**Issue by JHoule** [ShinraTech/CCDK#4]
I get the following error log:
```
1>------ Build started: Project: one_to_many, Configuration: Debug Win32 ------
1>  one_to_many.vcxproj -> C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\Debug\one_to_many.exe
1>  Uncatch exception when running
1>  Traceback (most recent call last):
1>    File "C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\\mcs\python\shinra.py", line 1167, in <module>
1>      main()
1>    File "C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\\mcs\python\shinra.py", line 1090, in main
1>      totalsize = p.getTotalFilesSize()
1>    File "C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\\mcs\python\shinra.py", line 415, in getTotalFilesSize
1>      totalsize += _getDataPackSize(self.projectdir, datapack)
1>    File "C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\\mcs\python\shinra.py", line 220, in _getDataPackSize
1>      for alias, file in _getFilesFromDataPack(basedir, datapack).items():
1>    File "C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\\mcs\python\shinra.py", line 215, in _getFilesFromDataPack
1>      raise RuntimeError("File mapping in data pack {0} refers to invalid path: {1}".format(datapack['id'], mapFsysPath))
1>  RuntimeError: File mapping in data pack DataPack refers to invalid path: C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\Release
1>  Script terminated
1>  cmd args: Namespace(archive_path='C:\\Shinra\\UserFiles', cloud_properties=None, command='setup', display_statistics=False, encoder_threads=2, gameid='Debug', gameport=55000, games_install_dir='C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install', log_file=None, log_level=None, max_encoding_frames=5, max_rendering_frames=3, projectid='one_to_many', show_window=False, store_path='C:\\Shinra\\Local', userid='aeris', videoport=60000)
1>  conf before = {'MaxEncodingFrames': 5, 'StorePath': 'C:\\Shinra\\Local', 'EncoderThreads': 2, 'ArchivePath': 'C:\\Shinra\\UserFiles', 'DisplayStatistics': False, 'MaxRenderingFrames': 3, 'ShowWindow': False, 'GamesInstallDir': 'C:\\Shinra\\Games', 'MCSPath': 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\mcs', 'CleanupOnInstall': False, 'Configuration': 'Debug', 'GPUCount': 1, 'OverwriteGameInstall': False}
1>  args.display_statistics False
1>  conf after = {'MaxEncodingFrames': 5, 'StorePath': 'C:\\Shinra\\Local', 'EncoderThreads': 2, 'ArchivePath': 'C:\\Shinra\\UserFiles', 'DisplayStatistics': False, 'MaxRenderingFrames': 3, 'ShowWindow': False, 'GamesInstallDir': 'C:\\Shinra\\Games', 'MCSPath': 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\mcs', 'CleanupOnInstall': False, 'Configuration': 'Debug', 'GPUCount': 1, 'OverwriteGameInstall': False}
1>  Uncatch exception when running
1>  Traceback (most recent call last):
1>    File "C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\\mcs\python\shinra.py", line 1167, in <module>
1>      main()
1>    File "C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\\mcs\python\shinra.py", line 1129, in main
1>      validateMCSSettings(conf)
1>    File "C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\\mcs\python\shinra.py", line 94, in validateMCSSettings
1>      raise RuntimeError("StorePath must be an existing directory.")
1>  RuntimeError: StorePath must be an existing directory.
1>  Script terminated
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: The command "cd C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\skeletons\one_to_many
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: C:\python34\python.exe C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\\mcs\python\shinra.py install -mcs-path C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\mcs -config Debug -games-install-dir C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\Install -overwrite -cleanup C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\skeletons\one_to_many\one_to_many.shinra
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: C:\python34\python.exe C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\\mcs\python\shinra.py setup -games-install-dir C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\Install one_to_many Debug aeris 55000 60000
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :VCEnd" exited with code -1.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

From the looks of it, it sounds like the script is expecting the "Release" directory to exist, whereas I only tried to build the Debug version of the executable.

Creating an empty 'Release' directory allows the script to proceed, but then complains about the following other missing variables/directories:
  StorePath = C:\Shinra\Local
  ArchivePath = C:\Shinra\UserFiles
  GamesInstallDir = C:\Shinra\Games

But then, it ultimately fails with a missing ShimD3D9.dll looked for in the CCDK/mcs directory.  Note that the script was looking for 'Shinra\x64\Debug\ShimD3D9.dll' even though I was building Win32-Debug.

**Comment by kengonakajima** [comment]
This is caused by remaining "Release" alias in one_to_many.shinra.
Now it is removed and should work (tested in my environment).
Please see v0.2.2.

Thanks!

**Comment by JHoule** [comment]
Sorry for taking so long to answer, but it looks like the issue is unresolved.

I've sync'd to both v0.2.2 and the latest (4 changes passed the v0.2.3, which only seem to include documentation fixes) and I get the same result.

**Comment by kengonakajima** [comment]
Can you copy and paste your "Output" tab in VisualStudio when you get error on build ?

**Comment by JHoule** [comment]
Here's what I get from a clean build and with a missing 'C:\Shinra' folder:

```
1>------ Build started: Project: one_to_many, Configuration: Debug Win32 ------
1>  pch.cpp
1>  Main.cpp
1>  Game.cpp
1>  Generating Code...
1>  one_to_many.vcxproj -> C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\Debug\one_to_many.exe
1>  delete file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\assets\\coinget.wav'
1>  delete file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\assets\\tahoma32.spritefont'
1>  Progression: 1%
1>  delete file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\assets\\tahoma9.spritefont'
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\backend.exe'
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\backend.ilk'
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\backend.pdb'
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\CloudCoreClient.dll'
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\D3D11.dll'
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\D3D9.dll'
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\d3dcompiler_47.dll'
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\DXGI.dll'
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\many_to_many.exe'
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\many_to_many.ilk'
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\many_to_many.pdb'
1>  delete file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\one_to_many.exe'
1>  Progression: 8%
1>  delete file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\one_to_many.ilk'
1>  Progression: 30%
1>  delete file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\one_to_many.pdb'
1>  Progression: 100%
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\one_to_one.exe'
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\one_to_one.ilk'
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\one_to_one.pdb'
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\vce.lib'
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\XInput1_3.dll'
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\XInput1_4.dll'
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\XInput9_1_0.dll'
1>  install startup: {'arguments': None, 'workDir': '', 'FileHooks': None, 'CustomProperties': {}, 'id': 'Debug', 'dataPackId': 'DataPack', 'numberOfPlayers': 4, 'multiconnection': True, 'executable': 'Debug\\one_to_many.exe'}
1>  offset: 288
1>  peHead: 17744
1>  Failed to create link 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\DXGI.dll' to 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\mcs\\Shinra\\x32\\Debug\\ShimDXGI.dll'. Will copy dll instead.
1>  Failed to create link 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\XInput9_1_0.dll' to 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\mcs\\Shinra\\x32\\Debug\\ShimXInput.dll'. Will copy dll instead.
1>  Failed to create link 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\XInput1_3.dll' to 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\mcs\\Shinra\\x32\\Debug\\ShimXInput.dll'. Will copy dll instead.
1>  Failed to create link 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\D3D11.dll' to 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\mcs\\Shinra\\x32\\Debug\\ShimD3D11.dll'. Will copy dll instead.
1>  Failed to create link 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\D3D9.dll' to 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\mcs\\Shinra\\x32\\Debug\\ShimD3D9.dll'. Will copy dll instead.
1>  Failed to create link 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\CloudCoreClient.dll' to 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\mcs\\Shinra\\x32\\Debug\\CloudCoreClient.dll'. Will copy dll instead.
1>  Failed to create link 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\XInput1_4.dll' to 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\mcs\\Shinra\\x32\\Debug\\ShimXInput.dll'. Will copy dll instead.
1>  Failed to create link 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\d3dcompiler_47.dll' to 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\mcs\\Shinra\\x32\\Debug\\d3dcompiler_47.dll'. Will copy dll instead.
1>  Script terminated
1>  cmd args: Namespace(archive_path='C:\\Shinra\\UserFiles', cloud_properties=None, command='setup', display_statistics=False, encoder_threads=2, gameid='Debug', gameport=55000, games_install_dir='C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install', log_file=None, log_level=None, max_encoding_frames=5, max_rendering_frames=3, projectid='one_to_many', show_window=False, store_path='C:\\Shinra\\Local', userid='aeris', videoport=60000)
1>  conf before = {'CleanupOnInstall': False, 'OverwriteGameInstall': False, 'DisplayStatistics': False, 'MaxRenderingFrames': 3, 'Configuration': 'Debug', 'EncoderThreads': 2, 'ArchivePath': 'C:\\Shinra\\UserFiles', 'GPUCount': 1, 'StorePath': 'C:\\Shinra\\Local', 'MCSPath': 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\mcs', 'ShowWindow': False, 'GamesInstallDir': 'C:\\Shinra\\Games', 'MaxEncodingFrames': 5}
1>  args.display_statistics False
1>  conf after = {'CleanupOnInstall': False, 'OverwriteGameInstall': False, 'DisplayStatistics': False, 'MaxRenderingFrames': 3, 'Configuration': 'Debug', 'EncoderThreads': 2, 'ArchivePath': 'C:\\Shinra\\UserFiles', 'GPUCount': 1, 'StorePath': 'C:\\Shinra\\Local', 'MCSPath': 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\mcs', 'ShowWindow': False, 'GamesInstallDir': 'C:\\Shinra\\Games', 'MaxEncodingFrames': 5}
1>  Uncatch exception when running
1>  Traceback (most recent call last):
1>    File "C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\\mcs\python\shinra.py", line 1167, in <module>
1>      main()
1>    File "C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\\mcs\python\shinra.py", line 1129, in main
1>      validateMCSSettings(conf)
1>    File "C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\\mcs\python\shinra.py", line 94, in validateMCSSettings
1>      raise RuntimeError("StorePath must be an existing directory.")
1>  RuntimeError: StorePath must be an existing directory.
1>  Script terminated
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: The command "cd C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\skeletons\one_to_many
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: C:\python34\python.exe C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\\mcs\python\shinra.py install -mcs-path C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\mcs -config Debug -games-install-dir C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\Install -overwrite -cleanup C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\skeletons\one_to_many\one_to_many.shinra
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: C:\python34\python.exe C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\\mcs\python\shinra.py setup -games-install-dir C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\Install one_to_many Debug aeris 55000 60000
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :VCEnd" exited with code -1.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

The executable (one_to_many.exe) gets built properly; it's the post-build scripts that fail, but those errors prevent launching/debugging the app (F5).

**Comment by ninoles** [comment]
For the one_to_many.shinra setting, I think we will probably need to have two .shinra, one_to_many_debug.shinra and one_to_many_release.shinra, and call the right one in the post build process.

We also probably need to have an initial setup that configure MCS correctly.  SDS 2.0 will have an installer, so that will be part of it.  In the mean time, just creating C:\Shinra will do the trick.

**Comment by JHoule** [comment]
As reported originally, creating 'C:\Shinra' is not sufficient.  But the error seems to have changed.

I currently get the following:
```
1>------ Build started: Project: one_to_many, Configuration: Debug Win32 ------
1>  one_to_many.vcxproj -> C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\Debug\one_to_many.exe
1>  delete file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\assets\\coinget.wav'
1>  delete file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\assets\\tahoma32.spritefont'
1>  Progression: 1%
1>  delete file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\assets\\tahoma9.spritefont'
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\CloudCoreClient.dll'
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\D3D11.dll'
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\D3D9.dll'
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\d3dcompiler_47.dll'
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\DXGI.dll'
1>  delete file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\one_to_many.exe'
1>  Progression: 8%
1>  delete file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\one_to_many.ilk'
1>  Progression: 30%
1>  delete file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\one_to_many.pdb'
1>  Progression: 100%
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\XInput1_3.dll'
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\XInput1_4.dll'
1>  delete old file 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\XInput9_1_0.dll'
1>  install startup: {'executable': 'Debug\\one_to_many.exe', 'CustomProperties': {}, 'multiconnection': True, 'dataPackId': 'DataPack', 'id': 'Debug', 'numberOfPlayers': 4, 'workDir': '', 'arguments': None, 'FileHooks': None}
1>  offset: 288
1>  peHead: 17744
1>  Failed to create link 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\XInput1_3.dll' to 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\mcs\\Shinra\\x32\\Debug\\ShimXInput.dll'. Will copy dll instead.
1>  Failed to create link 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\DXGI.dll' to 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\mcs\\Shinra\\x32\\Debug\\ShimDXGI.dll'. Will copy dll instead.
1>  Failed to create link 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\D3D9.dll' to 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\mcs\\Shinra\\x32\\Debug\\ShimD3D9.dll'. Will copy dll instead.
1>  Failed to create link 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\XInput1_4.dll' to 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\mcs\\Shinra\\x32\\Debug\\ShimXInput.dll'. Will copy dll instead.
1>  Failed to create link 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\CloudCoreClient.dll' to 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\mcs\\Shinra\\x32\\Debug\\CloudCoreClient.dll'. Will copy dll instead.
1>  Failed to create link 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\D3D11.dll' to 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\mcs\\Shinra\\x32\\Debug\\ShimD3D11.dll'. Will copy dll instead.
1>  Failed to create link 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\XInput9_1_0.dll' to 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\mcs\\Shinra\\x32\\Debug\\ShimXInput.dll'. Will copy dll instead.
1>  Failed to create link 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install\\one_to_many\\DataPack\\Debug\\d3dcompiler_47.dll' to 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\mcs\\Shinra\\x32\\Debug\\d3dcompiler_47.dll'. Will copy dll instead.
1>  Script terminated
1>  cmd args: Namespace(archive_path='C:\\Shinra\\UserFiles', cloud_properties=None, command='setup', display_statistics=False, encoder_threads=2, gameid='Debug', gameport=55000, games_install_dir='C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\Install', log_file=None, log_level=None, max_encoding_frames=5, max_rendering_frames=3, projectid='one_to_many', show_window=False, store_path='C:\\Shinra\\Local', userid='aeris', videoport=60000)
1>  conf before = {'MaxRenderingFrames': 3, 'GamesInstallDir': 'C:\\Shinra\\Games', 'GPUCount': 1, 'MaxEncodingFrames': 5, 'ShowWindow': False, 'DisplayStatistics': False, 'EncoderThreads': 2, 'ArchivePath': 'C:\\Shinra\\UserFiles', 'StorePath': 'C:\\Shinra\\Local', 'MCSPath': 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\mcs', 'Configuration': 'Debug', 'OverwriteGameInstall': False, 'CleanupOnInstall': False}
1>  args.display_statistics False
1>  conf after = {'MaxRenderingFrames': 3, 'GamesInstallDir': 'C:\\Shinra\\Games', 'GPUCount': 1, 'MaxEncodingFrames': 5, 'ShowWindow': False, 'DisplayStatistics': False, 'EncoderThreads': 2, 'ArchivePath': 'C:\\Shinra\\UserFiles', 'StorePath': 'C:\\Shinra\\Local', 'MCSPath': 'C:\\Users\\Jocelyn\\Downloads\\Code\\Shinra\\CCDK\\mcs', 'Configuration': 'Debug', 'OverwriteGameInstall': False, 'CleanupOnInstall': False}
1>  Uncatch exception when running
1>  Traceback (most recent call last):
1>    File "C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\\mcs\python\shinra.py", line 1167, in <module>
1>      main()
1>    File "C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\\mcs\python\shinra.py", line 1129, in main
1>      validateMCSSettings(conf)
1>    File "C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\\mcs\python\shinra.py", line 105, in validateMCSSettings
1>      checkMCSPath(conf['MCSPath'], conf['Configuration'])
1>    File "C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\\mcs\python\shinra.py", line 250, in checkMCSPath
1>      raise RuntimeError("Directory {0} does not contain MCS dll {1}.".format(mcsPath, relPath))
1>  RuntimeError: Directory C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\mcs does not contain MCS dll Shinra\x64\Debug\CloudCoreClient.dll.
1>  Script terminated
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: The command "cd C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\skeletons\one_to_many
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: C:\python34\python.exe C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\\mcs\python\shinra.py install -mcs-path C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\mcs -config Debug -games-install-dir C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\Install -overwrite -cleanup C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\skeletons\one_to_many\one_to_many.shinra
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: C:\python34\python.exe C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\\mcs\python\shinra.py setup -games-install-dir C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\Install one_to_many Debug aeris 55000 60000
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :VCEnd" exited with code -1.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

If we skip the symlink errors, which seem to have a fallback path, we get:
```
1>  RuntimeError: Directory C:\Users\Jocelyn\Downloads\Code\Shinra\CCDK\mcs does not contain MCS dll Shinra\x64\Debug\CloudCoreClient.dll.
```

Fair enough, I've looked at the directory with precompiled binaries, and while 32b has Debug+Release, 64b only has Release, and Debug is missing.  Looking at https://github.com/ShinraTech/CCDK/tree/master/mcs/Shinra seems to indicate that something might have been botched in the original submit (a directory is shown as 'x64/Release').

Maybe that could be the problem?

**Comment by kengonakajima** [comment]
hmm, weird, in my environment, it builds withoug x64/Debug..

**Comment by JHoule** [comment]
Well, the issue with 'x64/Debug' has been fixed 3 hours ago in e18e7d507da2eba09354971da89d7225bb664545, and I've verified that the previous commit (e77bbac38c3da081ca671af207c1d0bf6b353db4) still had the problem.

The only remaining problem is requiring 'C:\Shinra' directory structure to exist.  Could your Python script create it automatically?

The minimal set of directories that must exist are:
```
C:\Shinra\Games
C:\Shinra\Local
C:\Shinra\UserFiles
```
which correspond to 'GamesInstallDir', 'StorePath', and 'ArchivePath' respectively (in 'mcs\python\shinra.py').

If you don't automatically create those, you should document this requirement in the Setup.{en,ja}.md (or remove this requirement altogether).

**Comment by shinraSimon** [comment]
I don't know how Fabien and Nakajima-san want to handle this in the long term, but for now I am adding the directions to create the C:\Shinra directories prior to the first SDS setup.

**Comment by ninoles** [comment]
In current SDS, the GUI warn you about missing configuration elements.  The problem here is that SDS is never run: only the script is, which report the error.

SDS 2.0 will have it's own installer.  The configuration will either be down during installation or on the first run, either it is by script or through the GUI.

**Comment by JHoule** [comment]
If you want to, you could modify shinra.py to create those directories automatically (for the time being).

It's not the cleanest (as it clutters a dev's environment without them knowing), but it works.

```
--- a/mcs/python/shinra.py
+++ b/mcs/python/shinra.py
@@ -92,12 +92,18 @@ def setMCSSettings(conf):
 def validateMCSSettings(conf):
        if 'StorePath' in conf:
                if not os.path.isdir(conf['StorePath']):
+                       os.makedirs(conf['StorePath'])
+               if not os.path.isdir(conf['StorePath']):
                        raise RuntimeError("StorePath must be an existing directory.")
        if 'ArchivePath' in conf:
                if not os.path.isdir(conf['ArchivePath']):
+                       os.makedirs(conf['ArchivePath'])
+               if not os.path.isdir(conf['ArchivePath']):
                        raise RuntimeError("ArchivePath must be an existing directory.")
        if 'GamesInstallDir' in conf:
                if not os.path.isdir(conf['GamesInstallDir']):
+                       os.makedirs(conf['GamesInstallDir'])
+               if not os.path.isdir(conf['GamesInstallDir']):
                        raise RuntimeError("GamesInstallDir must be an existing directory.")
        services_path = conf.get('ServicesFile')
        if services_path:
```
